export const TABLE_DATA = {
  columns: {
    id: "ID",
    name: "Name",
    age: "Age",
    gender: "Gender",
    status: "Status",
  },
  data: [
    {
      id: 1,
      name: "John Doe",
      age: 30,
      gender: "Male",
      status: "Active",
    },
    {
      id: 2,
      name: "Jane Smith",
      age: 25,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 3,
      name: "Alice Johnson",
      age: 28,
      gender: "Female",
      status: "Active",
    },
    {
      id: 4,
      name: "Bob Brown",
      age: 35,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 5,
      name: "Charlie Black",
      age: 40,
      gender: "Male",
      status: "Active",
    },
    {
      id: 6,
      name: "Diana Prince",
      age: 32,
      gender: "Female",
      status: "Active",
    },
    {
      id: 7,
      name: "Eve Adams",
      age: 29,
      gender: "Female",
      status: "Active",
    },
    {
      id: 8,
      name: "Frank Castle",
      age: 37,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 9,
      name: "Grace Lee",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 10,
      name: "Hank Pym",
      age: 45,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 11,
      name: "Ivy Pepper",
      age: 27,
      gender: "Female",
      status: "Active",
    },
    {
      id: 12,
      name: "Jack Sparrow",
      age: 40,
      gender: "Male",
      status: "Active",
    },
    {
      id: 13,
      name: "Kara Zor-El",
      age: 28,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 14,
      name: "Luke Skywalker",
      age: 22,
      gender: "Male",
      status: "Active",
    },
    {
      id: 15,
      name: "Mia Wallace",
      age: 35,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 16,
      name: "Ned Stark",
      age: 40,
      gender: "Male",
      status: "Active",
    },
    {
      id: 17,
      name: "Olivia Pope",
      age: 36,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 18,
      name: "Peter Parker",
      age: 25,
      gender: "Male",
      status: "Active",
    },
    {
      id: 19,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Active",
    },
    {
      id: 20,
      name: "Wanda Maximoff",
      age: 30,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 21,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 22,
      name: "Clark Kent",
      age: 33,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 23,
      name: "Diana Prince",
      age: 29,
      gender: "Female",
      status: "Active",
    },
    {
      id: 24,
      name: "Natasha Romanoff",
      age: 34,
      gender: "Female",
      status: "Active",
    },
    {
      id: 25,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 26,
      name: "Stephen Strange",
      age: 40,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 27,
      name: "Wanda Maximoff",
      age: 32,
      gender: "Female",
      status: "Active",
    },
    {
      id: 28,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 29,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 30,
      name: "Clark Kent",
      age: 36,
      gender: "Male",
      status: "Active",
    },
    {
      id: 31,
      name: "Diana Prince",
      age: 29,
      gender: "Female",
      status: "Active",
    },
    {
      id: 32,
      name: "Natasha Romanoff",
      age: 34,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 33,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 34,
      name: "Wade Wilson",
      age: 36,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 35,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Active",
    },
    {
      id: 36,
      name: "Stephen Strange",
      age: 40,
      gender: "Male",
      status: "Active",
    },
    {
      id: 37,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 38,
      name: "Clark Kent",
      age: 33,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 39,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 40,
      name: "Natasha Romanoff",
      age: 34,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 31,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 42,
      name: "Natasha Romanoff",
      age: 34,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 43,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 44,
      name: "Wanda Maximoff",
      age: 32,
      gender: "Female",
      status: "Active",
    },
    {
      id: 45,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 46,
      name: "Clark Kent",
      age: 33,
      gender: "Male",
      status: "Active",
    },
    {
      id: 47,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 48,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Active",
    },
    {
      id: 49,
      name: "Stephen Strange",
      age: 39,
      gender: "Male",
      status: "Active",
    },
    {
      id: 50,
      name: "Natasha Romanoff",
      age: 36,
      gender: "Female",
      status: "Active",
    },
    {
      id: 51,
      name: "Wade Wilson",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 52,
      name: "Bruce Wayne",
      age: 42,
      gender: "Male",
      status: "Active",
    },
    {
      id: 53,
      name: "Clark Kent",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 54,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 55,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 56,
      name: "Tony Stark",
      age: 48,
      gender: "Male",
      status: "Active",
    },
    {
      id: 57,
      name: "Natasha Romanoff",
      age: 34,
      gender: "Female",
      status: "Active",
    },
    {
      id: 58,
      name: "Wade Wilson",
      age: 36,
      gender: "Male",
      status: "Active",
    },
    {
      id: 59,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 60,
      name: "Clark Kent",
      age: 33,
      gender: "Male",
      status: "Active",
    },
    {
      id: 61,
      name: "Diana Prince",
      age: 29,
      gender: "Female",
      status: "Active",
    },
    {
      id: 62,
      name: "Stephen Strange",
      age: 40,
      gender: "Male",
      status: "Active",
    },
    {
      id: 63,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 64,
      name: "Carol Danvers",
      age: 34,
      gender: "Female",
      status: "Active",
    },
    {
      id: 65,
      name: "Wade Wilson",
      age: 36,
      gender: "Male",
      status: "Active",
    },
    {
      id: 66,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 67,
      name: "Natasha Romanoff",
      age: 33,
      gender: "Female",
      status: "Active",
    },
    {
      id: 68,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Active",
    },
    {
      id: 69,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 70,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 71,
      name: "Clark Kent",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 72,
      name: "Wanda Maximoff",
      age: 32,
      gender: "Female",
      status: "Active",
    },
    {
      id: 73,
      name: "Bruce Wayne",
      age: 34,
      gender: "Male",
      status: "Active",
    },
    {
      id: 74,
      name: "Natasha Romanoff",
      age: 36,
      gender: "Female",
      status: "Active",
    },
    {
      id: 75,
      name: "Stephen Strange",
      age: 40,
      gender: "Male",
      status: "Active",
    },
    {
      id: 76,
      name: "Carol Danvers",
      age: 33,
      gender: "Female",
      status: "Active",
    },
    {
      id: 77,
      name: "Peter Parker",
      age: 29,
      gender: "Male",
      status: "Active",
    },
    {
      id: 78,
      name: "Diana Prince",
      age: 34,
      gender: "Female",
      status: "Active",
    },
    {
      id: 79,
      name: "Wade Wilson",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 80,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 81,
      name: "Natasha Romanoff",
      age: 36,
      gender: "Female",
      status: "Active",
    },
    {
      id: 82,
      name: "Clark Kent",
      age: 36,
      gender: "Male",
      status: "Active",
    },
    {
      id: 83,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Active",
    },
    {
      id: 84,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 85,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 86,
      name: "Wade Wilson",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 87,
      name: "Bruce Wayne",
      age: 34,
      gender: "Male",
      status: "Active",
    },
    {
      id: 88,
      name: "Natasha Romanoff",
      age: 33,
      gender: "Female",
      status: "Active",
    },
    {
      id: 89,
      name: "Clark Kent",
      age: 36,
      gender: "Male",
      status: "Active",
    },
    {
      id: 90,
      name: "Selina Kyle",
      age: 32,
      gender: "Female",
      status: "Active",
    },
    {
      id: 91,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 92,
      name: "Diana Prince",
      age: 29,
      gender: "Female",
      status: "Active",
    },
    {
      id: 93,
      name: "Wade Wilson",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 94,
      name: "Bruce Wayne",
      age: 34,
      gender: "Male",
      status: "Active",
    },
    {
      id: 95,
      name: "Natasha Romanoff",
      age: 33,
      gender: "Female",
      status: "Active",
    },
    {
      id: 96,
      name: "Clark Kent",
      age: 36,
      gender: "Male",
      status: "Active",
    },
    {
      id: 97,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Active",
    },
    {
      id: 98,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 99,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 100,
      name: "Wade Wilson",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 101,
      name: "Bruce Wayne",
      age: 34,
      gender: "Male",
      status: "Active",
    },
  ],
};
