export const TABLE_DATA = {
  columns: {
    id: "ID",
    name: "Name",
    age: "Age",
    gender: "Gender",
    status: "Status",
  },
  data: [
    {
      id: 1,
      name: "John Doe",
      age: 30,
      gender: "Male",
      status: "Active",
    },
    {
      id: 2,
      name: "Jane Smith",
      age: 25,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 3,
      name: "Alice Johnson",
      age: 28,
      gender: "Female",
      status: "Active",
    },
    {
      id: 4,
      name: "Bob Brown",
      age: 35,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 5,
      name: "Charlie Black",
      age: 40,
      gender: "Male",
      status: "Active",
    },
    {
      id: 6,
      name: "Diana Prince",
      age: 32,
      gender: "Female",
      status: "Active",
    },
    {
      id: 7,
      name: "Eve Adams",
      age: 29,
      gender: "Female",
      status: "Active",
    },
    {
      id: 8,
      name: "Frank Castle",
      age: 37,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 9,
      name: "Grace Lee",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 10,
      name: "Hank Pym",
      age: 45,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 11,
      name: "Ivy Pepper",
      age: 27,
      gender: "Female",
      status: "Active",
    },
    {
      id: 12,
      name: "Jack Sparrow",
      age: 40,
      gender: "Male",
      status: "Active",
    },
    {
      id: 13,
      name: "Kara Zor-El",
      age: 28,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 14,
      name: "Luke Skywalker",
      age: 22,
      gender: "Male",
      status: "Active",
    },
    {
      id: 15,
      name: "Mia Wallace",
      age: 35,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 16,
      name: "Ned Stark",
      age: 40,
      gender: "Male",
      status: "Active",
    },
    {
      id: 17,
      name: "Olivia Pope",
      age: 36,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 18,
      name: "Peter Parker",
      age: 25,
      gender: "Male",
      status: "Active",
    },
    {
      id: 19,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Active",
    },
    {
      id: 20,
      name: "Wanda Maximoff",
      age: 30,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 21,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 22,
      name: "Clark Kent",
      age: 33,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 23,
      name: "Diana Prince",
      age: 29,
      gender: "Female",
      status: "Active",
    },
    {
      id: 24,
      name: "Natasha Romanoff",
      age: 34,
      gender: "Female",
      status: "Active",
    },
    {
      id: 25,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 26,
      name: "Stephen Strange",
      age: 40,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 27,
      name: "Wanda Maximoff",
      age: 32,
      gender: "Female",
      status: "Active",
    },
    {
      id: 28,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 29,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 30,
      name: "Clark Kent",
      age: 36,
      gender: "Male",
      status: "Active",
    },
    {
      id: 31,
      name: "Diana Prince",
      age: 29,
      gender: "Female",
      status: "Active",
    },
    {
      id: 32,
      name: "Natasha Romanoff",
      age: 34,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 33,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 34,
      name: "Wade Wilson",
      age: 36,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 35,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Active",
    },
    {
      id: 36,
      name: "Stephen Strange",
      age: 40,
      gender: "Male",
      status: "Active",
    },
    {
      id: 37,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 38,
      name: "Clark Kent",
      age: 33,
      gender: "Male",
      status: "Inactive",
    },
    {
      id: 39,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 40,
      name: "Natasha Romanoff",
      age: 34,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 39,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 40,
      name: "Natasha Romanoff",
      age: 34,
      gender: "Female",
      status: "Inactive",
    },
    {
      id: 41,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 42,
      name: "Wanda Maximoff",
      age: 32,
      gender: "Female",
      status: "Active",
    },
    {
      id: 43,
      name: "Bruce Wayne",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 44,
      name: "Clark Kent",
      age: 33,
      gender: "Male",
      status: "Active",
    },
    {
      id: 45,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 46,
      name: "Tony Stark",
      age: 45,
      gender: "Male",
      status: "Active",
    },
    {
      id: 47,
      name: "Stephen Strange",
      age: 39,
      gender: "Male",
      status: "Active",
    },
    {
      id: 48,
      name: "Natasha Romanoff",
      age: 36,
      gender: "Female",
      status: "Active",
    },
    {
      id: 49,
      name: "Wade Wilson",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 50,
      name: "Bruce Wayne",
      age: 42,
      gender: "Male",
      status: "Active",
    },
    {
      id: 51,
      name: "Clark Kent",
      age: 35,
      gender: "Male",
      status: "Active",
    },
    {
      id: 52,
      name: "Diana Prince",
      age: 30,
      gender: "Female",
      status: "Active",
    },
    {
      id: 53,
      name: "Peter Parker",
      age: 28,
      gender: "Male",
      status: "Active",
    },
    {
      id: 54,
      name: "Tony Stark",
      age: 48,
      gender: "Male",
      status: "Active",
    },
    {
      id: 55,
      name: "Natasha Romanoff",
      age: 34,
      gender: "Female",
      status: "Active",
    },
  ],
};
